spring:
  application:
    name: idempotency
  datasource:
    url: jdbc:postgresql://localhost:5432/idempotency
    username: idempotency
    password: idempotency
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
