server:
  port: 8082          # each concept gets its own port so several can run at once

spring:
  application:
    name: caching
  datasource:
    url: jdbc:postgresql://localhost:5434/caching
    username: se
    password: se
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: MyHikariCP
  jpa:
    hibernate:
      ddl-auto: update      # dev only
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6381
  cache:
    type: caffeine

